# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titie',
            new_name='title',
        ),
    ]
